services:
  backend-spring:
    build:
      context: ../backend-spring
      dockerfile: Dockerfile.prod
    ports:
      - '8080:8080'
    environment:
      - STARTED_BY=Docker Compose
  frontend-angular:
    build:
      context: ../frontend-angular
      dockerfile: Dockerfile.prod
    ports:
      - '4200:80'
    depends_on:
      - backend-spring