services:
  backend-spring:
    build:
      context: ../backend-spring
      dockerfile: Dockerfile.prod
    ports:
      - '8080:8080'
  frontend-angular:
    build:
      context: ../frontend-angular
      dockerfile: Dockerfile.prod
    ports:
      - '4200:80'