services:
  backend-spring:
    build:
      context: ../../prodemics-backend-spring
      dockerfile: Dockerfile.prod
    ports:
      - '8080:8080'
    environment:
      - STARTED_BY=Docker Compose
  demo-spring-web-client:
    build:
      context: ../../demo-spring-web-client
      dockerfile: Dockerfile.prod
    ports:
      - '8081:8081'
    environment:
      - HOST_URL=backend-spring:8080
    depends_on:
      - backend-spring
  frontend-react:
    build:
      context: ../frontend-react
      dockerfile: Dockerfile.prod
    ports:
      - '4000:80'
    depends_on:
      - backend-spring