FROM node:14-alpine as build

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

RUN rm /app/.env.production

RUN cp /app/conf/.env.production.nginx /app/.env.production

RUN npm run build

# This is not required as we have full fledged NGINX server
# RUN cp /app/build/index.html /app/build/404.html

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]